version: '2'

services:
  php:
    build:
      context: ./php
      args:
        USER_NAME: 'ducanh'
        UID: '1000'
    container_name: php71
    volumes:
      - ./public_html/:/var/www/html/
    networks:
      docker-lamp:
#  php56:
#    extends:
#      service: php
#    build:
#      dockerfile: ./php56.Dockerfile
#    container_name: php56
#    entrypoint: ["echo", "Service disabled."]
  phpcs:
    build: ./phpci
    container_name: phpci
    tty: true
    volumes:
      - /tmp:/tmp
    networks:
      docker-lamp:
  httpd:
    build:
      context: ./httpd
    container_name: httpd
    volumes:
      - ./httpd/conf:/usr/local/apache2/conf/docker
      - ./public_html/:/var/www/html/
    ports:
      - "80:80"
      - "443:443"
    networks:
      docker-lamp:
  mariadb:
    image: mariadb:10.3
    container_name: maziadb
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "1"
    #ports:
    #  - "3306:3306"
    networks:
      docker-lamp:
        ipv4_address: 10.5.0.6
  redis:
    image: redis:5.0.5-alpine
    container_name: redis_da
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    entrypoint: redis-server --appendonly yes
    restart: always
    networks:
      docker-lamp:
#  mongodb:
#    image: mongo:4.0
#    container_name: mongodb
#    entrypoint: ["echo", "Service disabled."]
#    volumes:
#      - ./mongodb/data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: 1
#    #ports:
#    #  - "27017:27017"
#    networks:
#      docker-lamp:
networks:
  docker-lamp:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
